# Generated by Django 4.1.2 on 2022-10-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('surname', models.CharField(max_length=20, verbose_name='Surname')),
                ('grade', models.CharField(max_length=10, verbose_name='Grade')),
            ],
        ),
    ]
