# Generated by Django 4.1.2 on 2022-10-13 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
